### ISSUE TITLE
mask_source_crop

### ISSUE THREAD

**Issue by YYDSDD** [ljjcoder/EHTDI#5]
你好，非常感谢你们公布代码！

mask_source_crop 是什么啊，它一直显示有错误，我在其他地方也没找到关于mask_source_crop的定义。

![image](https://user-images.githubusercontent.com/90122071/204998768-329accc7-a6e3-4d6e-8763-2e118ad0553b.png)

**Comment by ljjcoder** [comment]
Hello, thank you for your interest in our work. mask_source_crop is a variable used during debugging, and it is not used in the final code. You can simply ignore it.
