### ISSUE TITLE
About s_t_y_bord in main_edge_enhance.py

### ISSUE THREAD

**Issue by TianX1nYu** [ljjcoder/EHTDI#8]
请问:
1、bord_mask_ts=(dilate_mask_ts-erode_mask_ts).cuda()*(1-mask_source_stack)的作用是为了去除源域的边界对吧？
2、s_t_y_bord=s_t_y*bord_mask_ts-(1-bord_mask_ts)您的代码里这句，标签减去掩码是在做什么？没有太看懂
3、loss_aug_st = self.loss(pred_s_t_mix_1[:1], s_t_y[:1].long())关于损失，这里为什么只对第一张图进行损失计算？

**Comment by ljjcoder** [comment]
1, bord_mask_ts是为了得到边缘的mask
2，s_t_y_bord得到边缘处的标签，其余的地方忽略
3，仅仅是为了让训练速度快一点，你可以尝试都算损失。
这部分在投稿后一周才做work，当时已经来不及将这部分内容写入文章，也就没有细致设计。整体代码源自做实验的初步尝试，很多实现非常随意，给您带来了不好的阅读体验，很抱歉。
